export const questions = [
  {
    id: 1,
    tag: '身世之谜',
    question: 'OpenClaw 在正式定名之前，经历过几次改名？正确的演变顺序是？',
    options: [
      { key: 'A', text: 'Clawdbot → Moltbot → OpenClaw' },
      { key: 'B', text: 'WhatsApp Relay → Clawdbot → Moltbot → OpenClaw' },
      { key: 'C', text: 'Moltbot → Clawdbot → OpenClaw' },
      { key: 'D', text: 'Clawd → Clawdbot → OpenClaw' },
    ],
    correctAnswer: 'B',
    funFact: 'OpenClaw 经历了 4 次命名！2025 年 11 月以"WhatsApp Relay"启动 → 2026 年 1 月 24 日开源发布命名"Clawdbot" → 1 月 27 日因 Anthropic 商标风险更名"Moltbot" → 1 月 30 日正式定名"OpenClaw"。Molt 意为"蜕皮"，象征 AI 智能体的迭代进化。',
  },
  {
    id: 2,
    tag: '开发者背景',
    question: 'OpenClaw 的核心开发者彼得·斯坦伯格在 2025 年 6 月创立了一家新公司，这家公司叫什么？',
    options: [
      { key: 'A', text: 'AI Claw Inc.' },
      { key: 'B', text: 'Amantus Machina' },
      { key: 'C', text: 'Lobster Labs' },
      { key: 'D', text: 'Agent First' },
    ],
    correctAnswer: 'B',
    funFact: 'Amantus Machina 是彼得·斯坦伯格为研发下一代超个性化 AI 智能体而创立的公司。公司名字源自拉丁语，大致意为"爱的机器"，体现了 AI 应该服务于人类的愿景。',
  },
  {
    id: 3,
    tag: '核心语言',
    question: 'OpenClaw 的核心代码主要使用哪种编程语言编写？',
    options: [
      { key: 'A', text: 'Python' },
      { key: 'B', text: 'Java' },
      { key: 'C', text: 'TypeScript' },
      { key: 'D', text: 'Rust' },
    ],
    correctAnswer: 'C',
    funFact: 'OpenClaw 核心使用 TypeScript 编写，这使得它能更好地与 Node.js 生态集成，也方便开发者扩展 Skills。这也是为什么它能快速兼容各种 MCP 服务器和现代 Web 工具。',
  },
  {
    id: 4,
    tag: 'Slogan',
    question: 'OpenClaw 的官方 Slogan 是什么？',
    options: [
      { key: 'A', text: '"AI That Thinks Like You"' },
      { key: 'B', text: '"The AI that actually does things"' },
      { key: 'C', text: '"Your Personal Digital Assistant"' },
      { key: 'D', text: '"Code Less, Do More"' },
    ],
    correctAnswer: 'B',
    funFact: '"The AI that actually does things" 精准概括了 OpenClaw 与普通聊天机器人的本质区别——它不是只"说"，而是真正"做"。这也是它能在 2026 年初爆火的核心卖点。',
  },
  {
    id: 5,
    tag: '增长速度',
    question: '2026 年 1 月到 3 月，OpenClaw 在 GitHub 上的 Stars 增长情况如何？',
    options: [
      { key: 'A', text: '从 1 万增长到 5 万' },
      { key: 'B', text: '从刚起步到突破 25 万，超越 React' },
      { key: 'C', text: '从 10 万增长到 50 万' },
      { key: 'D', text: '从 5 万增长到 15 万' },
    ],
    correctAnswer: 'B',
    funFact: 'OpenClaw 是开源社区成长最快的项目之一，90 天内 GitHub Stars 从刚起步突破 25 万，甚至超越了 React 的增速。这 90 天里它完成了 Gemini 多模型支持、PDF 原生处理、Kubernetes 企业级部署、200 多项安全强化等重磅更新。',
  },
  {
    id: 6,
    tag: '生态规模',
    question: '截至 2026 年初，OpenClaw 官方技能仓库 ClawHub 收录的 Skills 数量约为多少？',
    options: [
      { key: 'A', text: '约 570 个' },
      { key: 'B', text: '约 5700 个' },
      { key: 'C', text: '约 10000 个' },
      { key: 'D', text: '约 2000 个' },
    ],
    correctAnswer: 'B',
    funFact: 'ClawHub 的 Skills 数量已激增至约 5700 个！这得益于 MCP 协议作为"万能接口"的标准化设计，让社区开发者能快速贡献各种工具集成，从文件系统到 GitHub、Google Drive、Slack 等应有尽有。',
  },
  {
    id: 7,
    tag: '社区规模',
    question: '截至 2026 年 3 月，OpenClaw 社区技能包（Skills）数量超过多少？',
    options: [
      { key: 'A', text: '5700 个' },
      { key: 'B', text: '1 万个' },
      { key: 'C', text: '1.3 万个' },
      { key: 'D', text: '2 万个' },
    ],
    correctAnswer: 'C',
    funFact: '社区技能包超 1.3 万个！这得益于 MCP 协议作为"万能接口"的标准化设计，让社区开发者能快速贡献各种工具集成。从文件系统到 GitHub、Google Drive、Slack、飞书，几乎你想到的功能都有人写好了。',
  },
  {
    id: 8,
    tag: '技术支柱',
    question: 'OpenClaw 的四大核心技术支柱是以下哪一组？',
    options: [
      { key: 'A', text: 'API、SDK、CLI、GUI' },
      { key: 'B', text: 'IRSkills、MCP、RAG、Memory' },
      { key: 'C', text: 'Python、Node.js、Docker、K8s' },
      { key: 'D', text: 'Chat、Code、Search、Draw' },
    ],
    correctAnswer: 'B',
    funFact: 'IRSkills（技能库）、MCP（通信协议）、RAG（检索增强）、Memory（记忆系统）是 OpenClaw 的四大技术支柱。它们分别解决了"能做什么"、"怎么通信"、"怎么查资料"、"怎么记住"这四个核心问题。',
  },
  {
    id: 9,
    tag: '多 Agent 协作',
    question: 'OpenClaw 支持一种特殊的工作模式，可以同时启动多个 AI 子代理协作完成任务。这种模式被称为什么？',
    options: [
      { key: 'A', text: 'Swarm Mode（集群模式）' },
      { key: 'B', text: 'Team Mode（团队模式）' },
      { key: 'C', text: 'Sub-Agent Collaboration（子代理协作）' },
      { key: 'D', text: 'Hive Mind（蜂巢思维）' },
    ],
    correctAnswer: 'C',
    funFact: 'OpenClaw 支持子代理协作（Sub-Agent Collaboration）。你可以同时启动多个 AI：A 去网上查资料、B 把资料整理成笔记、C 写代码实现功能、D 最后汇总报告。就像拥有一个 AI 小团队！',
  },
  {
    id: 10,
    tag: '协议兼容',
    question: 'OpenClaw 通过 MCP 协议实现标准化通信，它兼容以下哪两种传输协议？',
    options: [
      { key: 'A', text: 'TCP 和 UDP' },
      { key: 'B', text: 'stdio 与 HTTP/SSE' },
      { key: 'C', text: 'WebSocket 和 gRPC' },
      { key: 'D', text: 'FTP 和 SMTP' },
    ],
    correctAnswer: 'B',
    funFact: 'OpenClaw 兼容 stdio（标准输入输出）与 HTTP/SSE（服务器发送事件）两种传输协议。这意味着它既可以通过本地命令行调用，也可以通过网络远程连接，灵活性极强。',
  },
  {
    id: 11,
    tag: '安全强化',
    question: '2026 年第一季度，OpenClaw 进行了一次重大安全更新，强化了多少项安全功能？',
    options: [
      { key: 'A', text: '约 50 项' },
      { key: 'B', text: '约 100 项' },
      { key: 'C', text: '约 200 多项' },
      { key: 'D', text: '约 500 项' },
    ],
    correctAnswer: 'C',
    funFact: '2026 年第一季度，OpenClaw 完成了 200 多项安全强化，这是它从"能跑起来"到"敢在生产环境使用"的关键转折点。包括权限隔离、操作审计、敏感数据保护等。',
  },
  {
    id: 12,
    tag: '创始人',
    question: 'OpenClaw 的创始人彼得·斯坦伯格（Peter Steinberger）之前是哪家知名公司的创始人？',
    options: [
      { key: 'A', text: 'GitHub' },
      { key: 'B', text: 'PSPDFKit' },
      { key: 'C', text: 'Vercel' },
      { key: 'D', text: 'Figma' },
    ],
    correctAnswer: 'B',
    funFact: '彼得·斯坦伯格是 PSPDFKit 的创始人，这是一家知名的 PDF SDK 公司。他在 2025 年 6 月创立了新公司 Amantus Machina（拉丁语意为"爱的机器"），专注于研发下一代超个性化 AI 智能体。',
  },
  {
    id: 13,
    tag: '搜索引擎',
    question: 'OpenClaw 默认使用哪个 API 进行联网搜索？（国内用户经常需要替换它）',
    options: [
      { key: 'A', text: 'Google Search API' },
      { key: 'B', text: 'Bing Search API' },
      { key: 'C', text: 'Brave Search API' },
      { key: 'D', text: 'DuckDuckGo API' },
    ],
    correctAnswer: 'C',
    funFact: 'OpenClaw 默认使用 Brave Search API 获取联网搜索能力。但由于服务器在国外且需要国际信用卡，国内用户通常需要配置替代方案（如 Tavi Search 或其他 MCP 搜索服务）。',
  },
  {
    id: 14,
    tag: '龙虾教',
    question: '在 2026 年的极客圈，围绕 OpenClaw 诞生的"龙虾教（Crustacean Cult）"的核心教条是什么？',
    options: [
      { key: 'A', text: '"Code is Law"' },
      { key: 'B', text: '"Memory is sacred"' },
      { key: 'C', text: '"AI First"' },
      { key: 'D', text: '"Open Source Forever"' },
    ],
    correctAnswer: 'B',
    funFact: '"Memory is sacred"（记忆即神圣）是龙虾教的核心教条。这体现了 OpenClaw 的持久化记忆系统是其区别于普通聊天机器人的关键特征——它能记住你的偏好、历史和上下文。',
  },
  {
    id: 15,
    tag: '终极题',
    question: '清华大学沈阳教授团队发布的 OpenClaw 研究报告中，总结 OpenClaw 具备的六大核心特点不包括以下哪项？',
    options: [
      { key: 'A', text: '范式重塑、自我信息' },
      { key: 'B', text: '自我进化、主动执行' },
      { key: 'C', text: '商业化变现、广告推送' },
      { key: 'D', text: '持久化、统一控制' },
    ],
    correctAnswer: 'C',
    funFact: 'OpenClaw 的六大核心特点是：范式重塑、自我信息、自我进化、主动执行、持久化、统一控制。"商业化变现、广告推送"完全不符合其开源、本地优先的核心理念。',
  },
];

export const QUESTION_TIME = 30; // 每题答题时间（秒）
export const CORRECT_SCORE = 10; // 答对基础分
export const BONUS_RANKS = 10; // 前几名有加分
